### ISSUE TITLE
Application features not working 

### ISSUE THREAD

**Issue by syamala27** [raghavtilak/VideoEditor#14]
`Issue: `  When I try to use the features, the toast "something went wrong!" appears.

Below I am sharing the videos of the problem. 

https://drive.google.com/file/d/1-9bYb5D8RPrptSQeWbzJb-LZ80dEtqjU/view?usp=sharing

https://drive.google.com/file/d/1-15PoTJf0W2qkb06FhfYL6yfRdFOmdWb/view?usp=sharing

**Comment by raghavtilak** [comment]
Please share the Logs,[https://github.com/raghavtilak/VideoEditor/blob/master/app/src/main/java/com/raghav/gfgffmpeg/MainActivity.java#L392](url).
Your Device name and Android Version too.

**Comment by syamala27** [comment]
device name `Lava Z4`
`android  11`
Here I am attaching the log :)
[log for video editor app.txt](https://github.com/raghavtilak/VideoEditor/files/7589637/log.for.video.editor.app.txt)

**Comment by raghavtilak** [comment]
I couldn't find anything erroneous in the Logs. I tried to replicate the issue in multiple devices, but its all working fine.

Does the app shows the toast "Something Went wrong" from the very first time after it is installed?
Or if it doesn't, then when exactly this toast is being shown?
If you have gone through the code, you might see a Log statement [here](https://github.com/raghavtilak/VideoEditor/blob/67fcee0d8d1a366a4384e9f32d14fdd4b88ae55e/app/src/main/java/com/raghav/gfgffmpeg/MainActivity.java#L392) . Try to capture that Log, and provide here the details.
