### ISSUE TITLE
Time scrubber (seekbar, time indicator) to Compose

### ISSUE THREAD

**Issue by raghavtilak** [raghavtilak/VideoEditor#23]

**Comment by Kardelio** [comment]
Thank you <3

**Comment by Kardelio** [comment]
I would guess the next ticket for compose could be the top bar with the `select video` and `save` button? if thats ok with you im happy to tackle that bad boy too <3

**Comment by raghavtilak** [comment]
Haha 😆 
Sure. Go for it. I will quickly create a ticket for it.
